openapi: 3.0.0
info:
  title: Витрина товаров API
  description: API для работы с товаром и корзиной
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /item/{id}:
    post:
      summary: Добавление товара в корзину
      description: Добавляет товар с указанным идентификатором в корзину и возвращает статус операции.
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор товара, который нужно добавить в корзину
        schema:
            type: integer
      responses:
        '200':
          description: Успешное добавление товара в корзину
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "товар добавлен в корзину!"
      '404':
          description: Товар не найден для добавления в корзину
      '500':
          description: Внутренняя ошибка сервера